[openai]
api_key = "01887710-4841-44f6-a693-fbc7fcb54c12"

[aimlapi]
api_key = "0f6cfe3d82254c6f83395b4a6bdc32fd"

# If using Microsoft Fabric, add these (based on README)
[fabric]
workspace = "your-fabric-workspace"
connection_string = "your-connection-string"